#pragma once
#define WIN32_LEAN_AND_MEAN
#include <algorithm>
#include <assert.h>
#include <cctype>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>